openapi: '3.0.0'
info:
  title: Profiled
  version: '1.0'
externalDocs:
  description: Daemon documentation
  url: https://confluence.mail.ru/display/RB/profiled.md

components:
  headers:
    x-bannerd-timeout:
      in: header
      name: x-bannerd-timeout
      schema:
        type: integer
      default: 100
      description: request timeout
  schemas:
    BannerdUserSettingsDebug:
      type: object
      properties:
        last_ts:
          type: integer
          format: int64
        debug:
          type: string
        bannerd_loc:
          type: string
        req:
          type: string
        expiration_ts:
          type: integer
          format: int64
    BannerdUserSettingsEye:
      type: object
      properties:
        last_ts:
          type: integer
          format: int64
        banners:
          type: array
          items:
            $ref: "#/components/schemas/EyeBannerEye"
        expiration_ts:
          type: integer
          format: int64
    EyeBannerEye:
      type: object
      properties:
        banner:
          type: integer
          format: int64
        cpm:
          type: integer
          format: int64
    ProductVisitEventPageType:
      type: string
      enum:
        - OTHER
        - HOME
        - SEARCHRESULTS
        - CATEGORY
        - PRODUCT
        - CART
        - PURCHASE
        - LAL
    ProductsVisitsVisit:
      type: object
      properties:
        shop_id:
          type: integer
          format: int64
        feed_id:
          type: integer
          format: int64
        product_id:
          type: string
        last_visit_ts:
          type: integer
          format: int64
        page_type:
          $ref: "#/components/schemas/ProductVisitEventPageType"
        score:
          type: integer
          format: int64
    ProductsVisitsVisit2:
      type: object
      properties:
        shop_id:
          type: integer
          format: int64
        feed_id:
          type: integer
          format: int64
        page_type:
          $ref: "#/components/schemas/ProductVisitEventPageType"
        products:
          type: array
          items:
            $ref: "#/components/schemas/Visit2Product"
    ProfiledBannerUserFeature:
      type: object
      properties:
        name:
          type: string
        value:
          $ref: "#/components/schemas/profileBUFeatureValues"
    ProfiledProfile:
      type: object
      properties:
        search_phrases:
          $ref: "#/components/schemas/profileSearchPhrases"
        products_visits:
          $ref: "#/components/schemas/profileProductsVisits"
        usual_locations:
          $ref: "#/components/schemas/profileUsualLocations"
        url_event_counters:
          $ref: "#/components/schemas/profileUrlEventCounters"
        last_known_locations:
          $ref: "#/components/schemas/profileLastKnownLocations"
        rb_odkl_apps:
          $ref: "#/components/schemas/profileUserApplications"
    ProfiledUserFeature:
      type: object
      properties:
        name:
          type: string
        value:
          $ref: "#/components/schemas/mlFeatureValue"
    SearchPhrasesQuery:
      type: object
      properties:
        id:
          type: integer
          format: int64
        mtime:
          type: integer
          format: int64
        phrase:
          type: string
          format: byte
        encoding:
          type: integer
          format: int64
        rb_source:
          type: integer
          format: int64
        rule:
          type: integer
          format: int64
        source:
          type: integer
          format: int64
        score:
          type: integer
          format: int64
    SearchPhrasesVector:
      type: object
      properties:
        version:
          type: integer
          format: int64
        phrases_count:
          type: integer
          format: int64
        sum:
          type: array
          items:
            type: integer
            format: int32
    UrlEventCount:
      type: object
      properties:
        id:
          type: integer
          format: int64
        count:
          type: integer
          format: int64
    UrlEventCountersUrl:
      type: object
      properties:
        url_object_type:
          type: integer
          format: int64
        url_object_id:
          type: string
        shows:
          type: integer
          format: int64
        clicks:
          type: integer
          format: int64
        goals:
          type: integer
          format: int64
        events:
          type: array
          items:
            $ref: "#/components/schemas/UrlEventCount"
        first_ts:
          type: integer
          format: int64
        last_ts:
          type: integer
          format: int64
    UserInterestsSourceCategory:
      type: object
      properties:
        interest_id:
          type: integer
          format: int64
        category_id:
          type: integer
          format: int64
        count:
          type: integer
          format: int64
    Visit2Product:
      type: object
      properties:
        product_id:
          type: string
        last_visit_ts:
          type: integer
          format: int64
        score:
          type: integer
          format: int64
    mlFeatureValue:
      type: object
      properties:
        keys:
          type: array
          items:
            type: integer
            format: int64
        vals:
          type: array
          items:
            type: number
            format: float
      title: >-
        Значение признака

        Категориальные признаки: выставляется только массив keys (сортировка + дельта-кодирование)

        Числовые признаки (плотное представление): выставляется только массив vals

        Числовые признаки (разреженное представление): выставляются оба массива, должны иметь одинаковый
                                                       размер, keys отсортирован и дельта кодирован
    profileBUFeatureLinkType:
      type: string
      enum:
        - Unknown
        - BannerId
        - DummyStrLink
      default: Unknown
      title: Типы связи баннер-пользователь
    profileBUFeatureValues:
      type: object
      properties:
        link_type:
          $ref: "#/components/schemas/profileBUFeatureLinkType"
        string_keys:
          type: array
          items:
            type: string
        uint32_keys:
          type: array
          items:
            type: integer
            format: int64
        values:
          type: array
          items:
            $ref: "#/components/schemas/mlFeatureValue"
      description: >-
        Значения признака для каждого ключа связи с баннером

        Для каждого конкретного значения типа связи заполняются либо строковые ключи, либо uint32-ключи

        Если тип ключей для данного типа связи выбран неверно, но они просто будут игнорироваться

        Количество ключей должно совпадать с количеством значений.
    profileBannerdUserSettings:
      type: object
      properties:
        debug:
          $ref: "#/components/schemas/BannerdUserSettingsDebug"
        eye:
          $ref: "#/components/schemas/BannerdUserSettingsEye"
    profileLastKnownLocations:
      type: object
      properties:
        locations:
          type: array
          items:
            $ref: "#/components/schemas/profileLocationMsg"
    profileLocationMsg:
      type: object
      properties:
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double
        location_provider:
          type: integer
          format: int64
        mtime:
          type: integer
          format: int64
    profileProductsVisits:
      type: object
      properties:
        visits:
          type: array
          items:
            $ref: "#/components/schemas/ProductsVisitsVisit"
        visits2:
          type: array
          items:
            $ref: "#/components/schemas/ProductsVisitsVisit2"
    profileProfiled:
      type: object
      properties:
        usual:
          $ref: "#/components/schemas/ProfiledProfile"
        cross:
          $ref: "#/components/schemas/ProfiledProfile"
        bannerd_user_settings:
          $ref: "#/components/schemas/profileBannerdUserSettings"
        user_interests_source:
          $ref: "#/components/schemas/profileUserInterestsSource"
        user_features:
          type: array
          items:
            $ref: "#/components/schemas/ProfiledUserFeature"
        banner_user_features:
          type: array
          items:
            $ref: "#/components/schemas/ProfiledBannerUserFeature"
    profileSearchPhrases:
      type: object
      properties:
        query_auto_increment:
          type: integer
          format: int64
        query:
          type: array
          items:
            $ref: "#/components/schemas/SearchPhrasesQuery"
        vector:
          $ref: "#/components/schemas/SearchPhrasesVector"
    profileUrlEventCounters:
      type: object
      properties:
        urls:
          type: array
          items:
            $ref: "#/components/schemas/UrlEventCountersUrl"
    profileUserApplicationRecord:
      type: object
      properties:
        application_id:
          type: string
          format: int64
        first_access_ts:
          type: integer
          format: int32
          title: fields 2-4 are reserved
        last_access_ts:
          type: integer
          format: int32
    profileUserApplications:
      type: object
      properties:
        applications:
          type: array
          items:
            $ref: "#/components/schemas/profileUserApplicationRecord"
    profileUserInterestsSource:
      type: object
      properties:
        categories:
          type: array
          items:
            $ref: "#/components/schemas/UserInterestsSourceCategory"
    profileUsualLocations:
      type: object
      properties:
        locations:
          type: array
          items:
            $ref: "#/components/schemas/profileUsualLocationsLocation"
    profileUsualLocationsLocation:
      type: object
      properties:
        latitude:
          type: number
          format: float
        longitude:
          type: number
          format: float
        radius:
          type: integer
          format: int64
        type:
          type: integer
          format: int64
        mtime:
          type: integer
          format: int64
        provider:
          type: integer
          format: int64

paths:
  /profile/v1.json:
    get:
      summary: get profile
      parameters:
        - in: query
          name: user_ids
          schema:
            type: array
            items:
              type: string
          required: false
          description: user ids for main profile with prefix
          style: form
          explode: false
          allowReserved: true
        - in: query
          name: all_user_ids
          schema:
            type: array
            items:
              type: string
          required: false
          description: user ids for cross-device profile with prefix
          style: form
          explode: false
          allowReserved: true
        - $ref: '#/components/headers/x-bannerd-timeout'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/profileProfiled'
  /profile/v1.proto:
    get:
      summary: get profile
      parameters:
        - in: query
          name: user_ids
          schema:
            type: array
            items:
              type: string
          required: false
          description: user ids for main profile with prefix
          style: form
          explode: false
          allowReserved: true
        - in: query
          name: all_user_ids
          schema:
            type: array
            items:
              type: string
          required: false
          description: user ids for cross-device profile with prefix
          style: form
          explode: false
          allowReserved: true
        - $ref: '#/components/headers/x-bannerd-timeout'
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                example: ""
  /api/tarantool.json:
    get:
      summary: get full profile data
      parameters:
        - in: query
          name: vk_id
          schema:
            type: array
            items:
              type: string
          required: false
          description: vk.com ids without prefix
          style: form
          explode: false
        - in: query
          name: ok_id
          schema:
            type: array
            items:
              type: string
          required: false
          description: ok.ru ids without prefix
          style: form
          explode: false
        - in: query
          name: vid
          schema:
            type: array
            items:
              type: string
          required: false
          description: vid ids without prefix
          style: form
          explode: false
        - in: query
          name: email
          schema:
            type: array
            items:
              type: string
          required: false
          description: email without prefix
          style: form
          explode: false
        - in: query
          name: device_id
          schema:
            type: array
            items:
              type: string
          required: false
          description: device ids with prefix
          style: form
          explode: false
        - in: query
          name: tel
          schema:
            type: array
            items:
              type: string
          required: false
          description: phone numbers without prefix
          style: form
          explode: false
        - $ref: '#/components/headers/x-bannerd-timeout'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tarantoolResponse'
